const char *wordList[WORD_COUNT] = {
    "RAMEN", "LAPTOP", "KARAOKE", "BOTTLE", "FOOTBALL", "GARDEN", "MARKET", "WINDOW", "BRIDGE", "CANDLE",
    "PLANET", "PRINTER", "GUITAR", "JOURNAL", "PYRAMID", "CIRCUS", "TUNNEL", "ISLAND", "CANYON", "CLOSET",
    "FURNACE", "BALLOON", "CAMPUS", "DOCTOR", "FARMER", "GADGET", "HAMMER", "JUNGLE", "KITCHEN", "LANTERN",
    "MIRROR", "NUGGET", "ORANGE", "PENCIL", "QUARRY", "ROCKET", "SHELTER", "TURTLE", "UMBRELLA", "VILLAGE",
    "WALRUS", "YACHT", "ZEBRA", "BANANA", "CANDLE", "DANCER", "EAGLE", "FISHING", "GIRAFFE", "HUNTER",
    "ICEBERG", "JACKET", "KANGAROO", "LANTERN", "MONSTER", "NEEDLE", "OYSTER", "PIRATE", "QUARTZ", "RABBIT",
    "SINGER", "TIGER", "UNICORN", "VULTURE", "WIZARD", "YELLOW", "ZEBRA", "ANCHOR", "BUNGEE", "CANYON",
    "DOLPHIN", "ELEVATOR", "FIREWORK", "GUITAR", "HORIZON", "IGLOO", "JOURNAL", "KITE", "LADDER", "MOUNTAIN",
    "NECKLACE", "OCTOPUS", "PENGUIN", "QUICKSAND", "RAINBOW", "SANDWICH", "TELESCOPE", "UNDERPASS", "VAMPIRE",
    "WATERFALL", "XYLOPHONE", "YOGURT", "ZUCCHINI", "BALCONY", "CARNIVAL", "DRAGON", "ECLIPSE", "FIREPLACE"
};
